name: test build

on:
  workflow_dispatch: {}

jobs:
  build-x86_64:
    name: build firecracker (x86_64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        tools/devtool -y build
        toolbox=$(uname -m)-unknown-linux-musl
        mkdir bin
        cp build/cargo_target/${toolbox}/debug/firecracker bin/firecracker-$(uname -m)
        cp build/cargo_target/${toolbox}/debug/jailer bin/jailer-$(uname -m)
    - name: Store firecracker binaries
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  build-aarch64:
    name: build firecracker (aarch64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      uses: uraimo/run-on-arch-action@v2.1.1
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
          echo \
            "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
            $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
          apt update
          apt install docker-ce docker-ce-cli containerd.io

          tools/devtool -y build
          toolbox=$(uname -m)-unknown-linux-musl
          mkdir bin
          cp build/cargo_target/${toolbox}/debug/firecracker bin/firecracker-$(uname -m)
          cp build/cargo_target/${toolbox}/debug/jailer bin/jailer-$(uname -m)
    - name: Store firecracker binaries
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  results:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-aarch64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download firecracker binaries
      uses: actions/download-artifact@v2
      with:
        name: firecracker-binaries
        path: bin
    - name: Check
      run: |
        file bin/*
