name: test build

on:
  workflow_dispatch: {}

jobs:
  build-x86_64:
    name: build firecracker (x86_64)
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Build"
      run: |
        tools/devtool -y build --release
        toolbox=$(uname -m)-unknown-linux-musl
        mkdir -p bin
        cp build/cargo_target/${toolbox}/release/firecracker bin/firecracker-$(uname -m)
        cp build/cargo_target/${toolbox}/release/jailer bin/jailer-$(uname -m)
    - name: "Store firecracker binaries"
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  build-aarch64:
    name: build firecracker (aarch64)
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Setup Cache Cargo"
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: "Setup Rust: aarch64-unknown-linux-musl"
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        override: true
        profile: minimal
        target: aarch64-unknown-linux-musl
    - name: "Setup Rust: aarch64-unknown-linux-gnu"
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        override: true
        profile: minimal
        target: aarch64-unknown-linux-gnu
    - name: "Install extra dependencies"
      run: |
        apt-get --quiet update
        apt-get --quiet --yes install \
          gcc-aarch64-linux-gnu
    - name: "Build: seccompiler"
      uses: actions-rs/cargo@v1.0.3
      with:
        command: build
        args: -p seccompiler --bin seccompiler-bin --target-dir build/seccompiler --target aarch64-unknown-linux-musl
    - name: "Build: firecracker"
      uses: actions-rs/cargo@v1.0.3
      with:
        command: build
        args: --release --target-dir build/cargo_target --target aarch64-unknown-linux-musl
    - name: "Build: jailer"
      uses: actions-rs/cargo@v1.0.3
      with:
        command: build
        args: --release -p jailer --target-dir build/cargo_target --target aarch64-unknown-linux-musl
    - name: "Post Build: Prepare artifacts"
      run: |
        mkdir -p bin
        cp \
          build/cargo_target/aarch64-unknown-linux-musl/release/firecracker \
          bin/firecracker-$(uname -m)
        cp \
          build/cargo_target/aarch64-unknown-linux-musl/release/jailer \
          bin/jailer-$(uname -m)
    - name: "Post build: Store firecracker binaries"
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  results:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-aarch64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download firecracker binaries
      uses: actions/download-artifact@v2
      with:
        name: firecracker-binaries
        path: bin
    - name: Check
      run: |
        file bin/*
