name: test build

on:
  workflow_dispatch: {}

jobs:
  build-x86_64:
    name: build firecracker (x86_64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        tools/devtool -y build
        toolbox=$(uname -m)-unknown-linux-musl
        mkdir -p bin
        cp build/cargo_target/${toolbox}/debug/firecracker bin/firecracker-$(uname -m)
        cp build/cargo_target/${toolbox}/debug/jailer bin/jailer-$(uname -m)
    - name: Store firecracker binaries
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  build-aarch64:
    name: build firecracker (aarch64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      uses: uraimo/run-on-arch-action@v2.1.1
      with:
        arch: aarch64
        distro: ubuntu20.04
        run: |
          apt-get update
          apt-get install -qy ca-certificates curl gnupg lsb-release

          curl https://sh.rustup.rs -sSf -o /tmp/rust-setup
          sh /tmp/rust-setup -y
          source $HOME/.cargo/env

          toolbox=$(uname -m)-unknown-linux-gnu

          echo $toolbox

          cargo build --target ${toolbox}
          mkdir -p bin
          cp build/cargo_target/${toolbox}/debug/firecracker bin/firecracker-$(uname -m)
          cp build/cargo_target/${toolbox}/debug/jailer bin/jailer-$(uname -m)
    - name: Store firecracker binaries
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  results:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-aarch64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download firecracker binaries
      uses: actions/download-artifact@v2
      with:
        name: firecracker-binaries
        path: bin
    - name: Check
      run: |
        file bin/*
