name: test build

on:
  workflow_dispatch: {}

jobs:
  build-x86_64:
    name: build firecracker (x86_64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: |
        tools/devtool -y build --release
        toolbox=$(uname -m)-unknown-linux-musl
        mkdir -p bin
        cp build/cargo_target/${toolbox}/debug/firecracker bin/firecracker-$(uname -m)
        cp build/cargo_target/${toolbox}/debug/jailer bin/jailer-$(uname -m)
    - name: Store firecracker binaries
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  build-aarch64:
    name: build firecracker (aarch64)
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Cache Cargo
      uses: actions/cache@v2.1.7
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
        key: cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Setup Rust
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: stable
        override: true
        profile: minimal
        target: aarch64-unknown-linux-musl
    - name: Build
      uses: actions-rs/cargo@v1.0.3
      with:
        command: build
        args: --release --locked --target aarch64-unknown-linux-musl
    - name: Post Build | Prepare artifacts [-nix]
      run: |
        mkdir -p bin
        cp \
          build/cargo_target/aarch64-unknown-linux-musl/release/firecracker \
          bin/firecracker-$(uname -m)
    - name: Store firecracker binaries
      uses: actions/upload-artifact@v2
      with:
        name: firecracker-binaries
        path: bin/*
        retention-days: 1
  results:
    runs-on: ubuntu-latest
    needs: [build-x86_64, build-aarch64]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download firecracker binaries
      uses: actions/download-artifact@v2
      with:
        name: firecracker-binaries
        path: bin
    - name: Check
      run: |
        file bin/*
